spring:
  application:
    name: api-gateway

  cloud:
    # We are not using a Config Server yet
    config:
      enabled: false

    gateway:
      routes:

        # ==============================
        # USER SERVICE
        # ==============================
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**

        # ==============================
        # EVENT SERVICE
        # ==============================
        # Your event-service is currently
        # running on port 8084.
        - id: event-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/events/**,/api/v1/event-centers/**

        # ==============================
        # BOOKING SERVICE
        # ==============================
        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/bookings/**

        # ==============================
        # NOTIFICATION SERVICE
        # ==============================
        # Change 8085 if your notification-service
        # uses a different port.
        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/notifications/**


# ==========================================
# API GATEWAY SERVER
# ==========================================
server:
  port: 8080


# ==========================================
# ACTUATOR
# ==========================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    health:
      show-details: always
